### ISSUE TITLE
Package Upload content upload github link required

### ISSUE THREAD

**Issue by just007in** [ECE-461-Project/ECE461_Project_Part2#78]
If the user uploads a local package, does the package.json necessarily have a github link?

**Comment by priyankapereira1** [comment]
yes! spec says we can assume it's "in the style of an npm package" and we are allowed to assume it's in the 'homepage' field. I am changing it to be the 'homepage' one because of this piazza post: https://piazza.com/class/lc9qx1w86k643t/post/230.

rn my code uses 'repository: url:' fields, and I am changing this on the next PR

**Comment by priyankapereira1** [comment]
plan rn: (I'm using homepage as default and checking repository:url second, and if neither are set return fail code)

**Comment by priyankapereira1** [comment]
oh also, the URL parsing in score calculations I have updated to trim/fix URL inputs, so any weird homepage URLs are fixed, scored, and put in the database that way
